# Generated by Django 2.2.7 on 2019-11-26 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='机房名称')),
                ('linkphone', models.CharField(blank=True, max_length=16, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='机房地址')),
                ('network_segment', models.TextField(blank=True, null=True, verbose_name='网段')),
                ('bandwidth', models.CharField(blank=True, max_length=64, null=True, verbose_name='机房带宽')),
                ('operator', models.PositiveIntegerField(blank=True, choices=[(0, '电信'), (1, '联通'), (2, '移动'), (3, '铁通'), (4, '小带宽')], null=True, verbose_name='运营商')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': 'IDC资产表',
                'verbose_name_plural': 'IDC资产表',
                'db_table': 'ops_idc',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='标签')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产标签表',
                'verbose_name_plural': '资产标签表',
                'db_table': 'ops_tags',
            },
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, db_index=True, null=True, unique=True, verbose_name='管理IP')),
                ('mac', models.CharField(blank=True, max_length=128, null=True, verbose_name='MAC地址')),
                ('status', models.PositiveIntegerField(blank=True, choices=[(0, '下架'), (1, '启用'), (2, '故障'), (3, '未使用'), (4, '未知')], default=1, verbose_name='设备状态')),
                ('asset_type', models.PositiveIntegerField(blank=True, choices=[(1, '物理机'), (2, '虚拟机'), (3, 'Docker')], verbose_name='资产类型')),
                ('system', models.CharField(blank=True, max_length=128, verbose_name='操作系统')),
                ('is_pass', models.BooleanField(blank=True, default=False, verbose_name='Ping')),
                ('verify_type', models.SmallIntegerField(blank=True, choices=[(0, 'password'), (1, 'key')], default=0, verbose_name='验证类型')),
                ('sshuser', models.CharField(blank=True, max_length=64, null=True, verbose_name='SSH用户')),
                ('sshport', models.CharField(blank=True, default=22, max_length=5, null=True, verbose_name='SSH端口')),
                ('sshpwd', models.CharField(blank=True, max_length=256, null=True, verbose_name='密码验证')),
                ('sshkey', models.CharField(blank=True, max_length=256, null=True, verbose_name='密匙')),
                ('mysql_user', models.CharField(blank=True, default='root', max_length=64, verbose_name='MYSQL用户')),
                ('mysql_pwd', models.CharField(blank=True, max_length=128, null=True, verbose_name='MYSQL密码')),
                ('mysql_port', models.CharField(blank=True, default=3306, max_length=6, null=True, verbose_name='MYSQL端口')),
                ('ftp_port', models.CharField(blank=True, max_length=5, null=True, verbose_name='FTP端口')),
                ('remark', models.TextField(blank=True, verbose_name='备注信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('change_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('maturity_time', models.DateField(blank=True, null=True, verbose_name='到期时间')),
                ('add_time', models.DateField(blank=True, null=True, verbose_name='上架时间')),
                ('host_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.Assets', verbose_name='宿主机')),
                ('idc', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.IDC', verbose_name='所属机房')),
            ],
            options={
                'verbose_name': '总资产表',
                'verbose_name_plural': '总资产表',
                'db_table': 'ops_assets',
            },
        ),
    ]
