# Generated by Django 2.2.7 on 2019-11-26 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='opsuser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_assets', to=settings.AUTH_USER_MODEL, verbose_name='管理者'),
        ),
        migrations.AddField(
            model_name='assets',
            name='tags',
            field=models.ManyToManyField(blank=True, db_constraint=False, to='assets.Tags', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='assets',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_assets', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
    ]
